version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  AfterInstall:
    - location: scripts/install-dependencies.sh

  ApplicationStart:
    - location: scripts/start-server.sh
